### ISSUE TITLE
RecyclerView 曝光统计 不准确

### ISSUE THREAD

**Issue by ikkyu0319** [growingio/AndroidDemo#2]
参考https://growingio.kf5.com/hc/kb/article/1334862/

设置了setHasStableIds(true)

`  @Override    
    public long getItemId(int position) {       
        return position;    
    }`

重写了getItemId

`@Override
    public void onBindViewHolder(BaseViewHolder helper, int position) {
        super.onBindViewHolder(helper, position);
        UgcDetail ugcDetail ==getItem(position);
        if (ugcDetail != null && (!mUgcIds.contains(helper.getAdapterPosition()))) {
            mUgcIds.add(helper.getAdapterPosition());
            GrowingIO.getInstance().markViewImpression(
                    new ImpressionMark(helper.itemView, GioEvent.biuContentImpr_event)
                            .setGlobalId(String.valueOf(position))
                            .setVariable(new GioJson().put("contentPosition_var", helper.getAdapterPosition()).put("id", ugcDetail.getId()).put("ids", mUgcIds.toString()).build()).setVisibleScale(0.2f).setDelayTimeMills(200));
        }
    }`

上下滑动，统计会重复
产品要求，出现了，上下滑动，只有未统计的，才统计

Help～～

**Comment by IceMimosa** [comment]
@lizwangying

**Comment by lizwangying** [comment]
半自动 imp 的统计触发时机是， view 从屏幕中出现。上下滚动，会造成头部和顶部的 item 被统计。 
可以给您提供一个 针对 RecyclerView 的demo, 如下：

```java


public class RecyclerViewImpActivity extends Activity {

    RecyclerView recyclerView;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_imp_recycler);
        recyclerView = findViewById(R.id.rv_imp);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        Adapter adapter = new Adapter();
        recyclerView.setAdapter(adapter);
        findViewById(R.id.btn_imp_notify).setOnClickListener(v -> {
            adapter.notifyDataSetChanged();
        });
    }

    private static class Adapter extends RecyclerView.Adapter<ViewHolder>{

        @NonNull
        @Override
        public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
            View rootView = LayoutInflater.from(parent.getContext()).inflate(R.layout.list_item_imp, parent, false);
            return new ViewHolder(rootView);
        }

        @Override
        public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
            holder.left.setText("position: " + position);
            JSONObject jsonObject = new JSONObject();
            try {
                jsonObject.put("position", position);
            } catch (JSONException e) {
                e.printStackTrace();
            }
            if (position == 0){
                LogUtil.d("LDK", "herererere");
            }
            GrowingIO.getInstance().markViewImpression(new ImpressionMark(holder.left, "列表项:" + position)
                    .setGlobalId(String.valueOf(position))
                    .setVariable(jsonObject));
        }

        @Override
        public int getItemCount() {
            return 100;
        }
    }

    private static class ViewHolder extends RecyclerView.ViewHolder{
        private TextView left, middle, right;

        public ViewHolder(View itemView) {
            super(itemView);
            left = itemView.findViewById(R.id.tv_left);
            middle = itemView.findViewById(R.id.tv_middle);
            right = itemView.findViewById(R.id.tv_right);
            middle.setText("中间部分");
            right.setText("两边部分");
        }
    }
}

```

![image](https://user-images.githubusercontent.com/13509775/71571742-cdc90680-2b16-11ea-9e62-34244cac6740.png)

**Comment by lizwangying** [comment]
另外，SDK 相关问题可以直接提交工单，接到反馈可能会更快。
我们的帮助文档，希望能在产品使用上帮助到您。

半自动IMP文档：
https://docs.growingio.com/docs/developer-manual/sdkintegrated/android-sdk/android-imp

**Comment by lizwangying** [comment]
@ikkyu0319   忘记艾特了。。。。。
